apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: samplecondition-
spec:
  entrypoint: doNothing
  templates:
  - name: doNothing
    steps:
    # Add 1 and 2 to equal 3
    - - name: add-numbers
        template: add-numbers
    # evaluate the result and decise what to do (multiplication or subtraction)
    - - name: multiply
        template: multiply                                  # invoke multiplication when addition result is 3
        when: "{{steps.add-numbers.outputs.result}} == 3"
      - name: subtract
        template: subtract                                  # invoke subtraction when addition result is 2
        when: "{{steps.add-numbers.outputs.result}} == 2"

  - name: add-numbers
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        value1 = 1
	value2 = 2
	result = value1 + value2
        print(result)

  - name: multiply
    container:
      image: python:alpine3.6
      command: [python]
      source: |
	value1 = 1
	value2 = 2
        result = value1 * value2
        print(result)

  - name: subtract
    container:
      image: python:alpine3.6
      command: [python]
      source: |
        value1 = 100
	value2 = 50
	result = value1 - value2
        print(result)
